### ISSUE TITLE
nx-builders:tsc - IPC signals not received on windows

### ISSUE THREAD

**Issue by yannickadam** [tailoredmedia/backend-nx-skeleton#1]
Hi! 

I've tried on both windows and wsl.
runAfterWatch (and also typescript path swap) are not being run after a successful transpile. 
process.send is not defined in tsc-watch.

This seems to be related to the way Execa spawns child processes.

As a quick test, changing: 
```const instance = this.manager.addPersistent(execa(this.paths.tscWatch, args, spawnOptions))```
to 
```const instance = this.manager.addPersistent(execa.node('node_modules/tsc-watch', args, spawnOptions))```

seems to fix the issue.

**Comment by cenk1cenk2** [comment]
Hello @yannickadam,

Please try out the latest version for better Windows support, I am not sure if this exactly solves this one but on the client's machines, it has been confirmed that builders to working on Windows.
