### ISSUE TITLE
Q: Dataloader only with code first?

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [tailoredmedia/backend-nx-skeleton#2]
I have a question concerning @webundsoehne/nestjs-graphql-typeorm-dataloader the example is with @ObjectType which indicates code first, also the @Field decorator.
Can this package be used with schema first approach as well?

**Comment by cenk1cenk2** [comment]
Hello @sschneider-ihre-pvs,

Unfortunately, since we strictly use the code first approach, it has no support for the schema first approach. The way it works is by assigning metadata to the class-based entities or input/output types where this would be resolved by the generic middleware.
